import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  ball1: {
    width: 20,
    height: 20,
    backgroundColor: "#00cba9",
    borderRadius: 100,
    position: "absolute",
    top: 670,
    left: 100,
    opacity: 0.8,
  },
  ball2: {
    width: 20,
    height: 20,
    backgroundColor: "#00cba9",
    borderRadius: 100,
    position: "absolute",
    top: 670,
    left: 80,
    opacity: 0.8,
  },
  ball3: {
    width: 20,
    height: 20,
    backgroundColor: "#00cba9",
    borderRadius: 100,
    position: "absolute",
    top: 670,
    left: 60,
    opacity: 0.8,
  },
  ball4: {
    width: 20,
    height: 20,
    backgroundColor: "#00cba9",
    borderRadius: 100,
    position: "absolute",
    top: 670,
    left: -10,
    opacity: 0.8,
  },
  ball5: {
    width: 20,
    height: 20,
    backgroundColor: "#00cba9",
    borderRadius: 100,
    position: "absolute",
    top: 670,
    left: -50,
    opacity: 0.8,
  },
  ball6: {
    width: 20,
    height: 20,
    backgroundColor: "#00cba9",
    borderRadius: 100,
    position: "absolute",
    top: 670,
    left: -100,
    opacity: 0.8,
  },
  ball7: {
    width: 20,
    height: 20,
    backgroundColor: "#00cba9",
    borderRadius: 100,
    position: "absolute",
    top: 670,
    left: -200,
    opacity: 0.8,
  },

  bgImg: {
    width: "100%",
    height: 150,
    resizeMode: "container",
    position: "absolute",
    bottom: 0,
    left: 0,
  },
  container2: {
    width: "80%",
    flex: 1,
  },
  header: {
    height: 80,
    borderBottomWidth: 1,
    width: "100%",
    padding: 20,
    justifyContent: "space-between",
    flexDirection: "row",
  },
  infoHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  subTitle: {
    fontSize: 16,
    color: "#000",
  },

  item: {
    backgroundColor: "#fff",
    borderRadius: 5,
    padding: 20,
    marginTop: 20,
  },
  topInfo: {
    width: "90%",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    marginBottom: 20,
  },
  info: {
    width: "100%",
    alignItems: "center",
    flexDirection: "row",
  },
  imgBuy: {
    height: 300,
    width: "100%",
  },
  ButText: {
    textAlign: "center",
    fontWeight: "bold",
    color: "#475F7D",
    marginTop: 20,
  },
  button: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FC783F",
    padding: 15,
    borderRadius: 5,
    marginTop: 20,
  },
  buttonText: {
    fontWeight: "bold",
    textTransform: "uppercase",
  },
});
